### ISSUE TITLE
Do not put binaries into Git repos

### ISSUE THREAD

**Issue by probonopd** [REDasmOrg/REDasm#11]
Please do not put binaries into Git repos, but upload to https://github.com/REDasmOrg/REDasm/releases instead.

https://github.com/probonopd/uploadtool can do this for you with ease.

Reference:
* https://help.github.com/articles/distributing-large-binaries/

**Comment by Dax89** [comment]
Sorry for the super late reply!
Binaries are now stored in a dedicated server: https://redasm.io/download
