### ISSUE TITLE
Crash on Call References selection in Call Graph

### ISSUE THREAD

**Issue by nlroth** [REDasmOrg/REDasm#19]
![crash](https://user-images.githubusercontent.com/48253208/53817718-1f732580-3f34-11e9-820f-ce2db663ade7.jpg)
Repeatable: Open Etcher-Portable-1.4.5-x86.exe in REDasm - Click on letter 'p' of word 'push' at 004011EF and then select Call Graph, right click on "00401245 call sub_4011ef"  and select Cross References: REDasm either hangs or crashes.
PC is a Lenovo T440p with 8GB RAM and Samsung 860PRO SSD.

**Comment by Dax89** [comment]
I can reproduce, thanks for reporting!

**Comment by Dax89** [comment]
Fixed in https://github.com/REDasmOrg/REDasm/commit/acda2b065f9a32fdd5a71e576ca047f006c35f81
