### ISSUE TITLE
Basic block title

### ISSUE THREAD

**Issue by tathanhdinh** [REDasmOrg/REDasm#21]
The basic block titles `Condition TRUE/FALSE` or `Unconditional` is now set as, for example:

![redasm_cfg](https://user-images.githubusercontent.com/79418/54136303-ce739d80-441b-11e9-98b5-418e49c25d3a.png)

IMHO, we should set the title of edges instead of basic blocks since there may exist different conditions for jumping to a basic block, e.g. basic block at `0x402285` is also a `Condition FALSE` if we consider the `jne` at 0x402283.

I've tried to handle this myself but I'm still not familiar with the code base yet, sorry and many thanks for any help.

**Comment by Dax89** [comment]
Like this?

![Screenshot_20190311_203101](https://user-images.githubusercontent.com/1503603/54152078-a183b280-443c-11e9-950a-95c7cc911b2a.png)

**Comment by tathanhdinh** [comment]
Yes, thank you.
