### ISSUE TITLE
Heads-up: REDasm is now packaged in FreeBSD

### ISSUE THREAD

**Issue by 0mp** [REDasmOrg/REDasm#22]
https://www.freshports.org/devel/redasm

**Comment by Dax89** [comment]
Great, Thanks!

I will mention that in the "Downloads" section

**Comment by alexmyczko** [comment]
No worries, Debian's getting one too (soon): http://phd-sid.ethz.ch/debian/redasm/

**Comment by Dax89** [comment]
I have added a new section for packaged versions here: https://redasm.io/download

**Comment by 0mp** [comment]
@Dax89 Awesome! Thanks a lot!
