### ISSUE TITLE
Disassembly stops when decodeInstruction fails

### ISSUE THREAD

**Issue by Altenius** [REDasmOrg/REDasm#23]
While working on a SuperH assembler plugin, I found some annoying behavior.

This looks like intended behavior, but when disassembling with the binary format and address 0 is not an instruction, the disassembly view will usually have a 'db' mnemonic followed by the invalid opcode. In my case, I'm disassembly a ROM dump that has an interrupt vector at address 0 that holds information about interrupt handlers. It would be useful if every byte was accounted for in the disassembly view. In the case that disassembly fails, the disassembly view would be filled with 'db' mnemonics and the user could manually convert an address to code.

**Comment by Dax89** [comment]
Yes, it's the default behavior, the standard algorithm is pretty conservative.

There are (at least) two ways to solve this:
- I can mark [AssemblerAlgorithm::disassembleInstruction()](https://github.com/REDasmOrg/REDasm-Library/blob/master/redasm/plugins/assembler/algorithm/algorithm.h#L31) virtual so anyone can override the default behavior. (Custom algorithms can be created by overriding `AssemblerPlugin::createAlgorithm()`)

- With the latest nightlies you can create a loader with segmentation info, symbols and entry point information for that kind of ROM dumps (even if they are raw binaries) and let redasm follow the code.

**Comment by Dax89** [comment]
I have made some changes to the algorithm: you should be able to continue the analysis even if one or more opcodes are not valid
