### ISSUE TITLE
Linking fails on i386 when built with Clang 8.0.0 on FreeBSD

### ISSUE THREAD

**Issue by danfe** [REDasmOrg/REDasm#26]
When I try to build version 2.1 on FreeBSD/i386 with recent Clang 8.0.0, the final executable fails to link because it cannot resolve `REDasm::bitscount<unsigned int>::value`, where `unsigned int` is misspelled `size_t` which is 4 bytes on 32-bit architectures.

Inspecting generated object files with `nm -gC` indeed shows there is an unresolved reference in `redasm/database/database.cpp.o`.  But looking at the definition, it is `constexpr` so it supposed to be substituted at compile time, and no reference generated at all.

(There is a minor style bug, however: `sizeof()` returns `std::size_t` per C++ standard, so correct template should probably look like this (pseudo-patch below):

```diff
-template<typename T> struct bitscount { static constexpr T value = sizeof(T) * CHAR_BIT; };
+template<typename T> struct bitscount { static constexpr std::size_t value = sizeof(T) * CHAR_BIT; };
```
There are three invocations of `bitscount<size_t>::value` in `database.cpp`, but only one is causing the bug, the one in `Database::save()` method on line 31:
```c++
        Serializer<u32>::write(ofs, bitscount<size_t>::value);
```
If I change the code to this:
```c++
        std::size_t foo = bitscount<size_t>::value;
        Serializer<u32>::write(ofs, foo);
```
then it links fine on i386.  The problem does not manifest itself on amd64, so it might be a bug in Clang rather than an actual problem with the code.  I'm providing this analysis for reference only, and do not suggest committing ugly work-arounds, albeit I'd have to do something like this to unbreak FreeBSD port on i386. :-(

**Comment by Dax89** [comment]
It compiles if I cast `value` as `u32` type?
```cpp
Serializer<u32>::write(ofs, static_cast<u32>(bitscount<size_t>::value));
```

This field is just for check the "bitness" of the stored database: this value can be only equal to 16, 32, 64 bits.
If yes, I will commit the changes on LibREDasm repository

**Comment by danfe** [comment]
Yes, `static_cast<32>()` makes compiler behave well. :-)  Even `bitscount<size_t>::value + 0` helps.  So if compiler is forced to use the value somehow, it correctly expands the `constexpr` instead of generating external reference.

**Comment by Dax89** [comment]
Ok, I have pushed those changes, thanks!
