### ISSUE TITLE
Try to fix size_t vs u64 type conflict (part 2)

### ISSUE THREAD

**Issue by danfe** [REDasmOrg/REDasm#27]
As promised earlier, second part of fixes to unbreak the build on i386.

There are two types of bugs in the `widgets/disassemblerlistingview/disassemblertextview.cpp` file:

- Type mismatch between `ListingCursor` class methods like `currentLine()`, `currentColumn()`, `moveTo()`, `select()`, which all operate on `size_t` data and `ListingRenderer` class method `getLastColumn()` which takes and returns `u64` for some reason (ideally it should be fixed to use `size_t` instead, which is wide enough on 64-bit to hold even ridiculous sizes, and sane enough on 32-bit where 64-bit operations are needlessly expensive and 32-bitness won't allow to address enough address space to hold amount of data that would require 64-bit wide type).  These two types are not portably interchangeable, as their sizes differ on 32-bit and 64-bit architectures.

- Several calls like `std::max(static_cast<u64>(0), ...)` for which Clang complains that **taking the max of unsigned zero and a value is always equal to the other value [-Wmax-unsigned-zero]; remove call to max function and unsigned zero argument**.

Consider the [attached patch](https://github.com/REDasmOrg/REDasm/files/3172980/types-patch-2.txt).  It removes `u64` abuse and uses `size_t` as appropriate, and removes needless calls to `std::max()`.  These are the last changes that allow to make version 2.1 to compile and link on both i386 and amd64.

**Comment by Dax89** [comment]
I can change `getLastColumn()` to size_t too so it's consistent to `Position`, `currentLine()` and `currentColumn()`

**Comment by danfe** [comment]
That would be much better than sporadic casts scattered here and there, thank you!

**Comment by Dax89** [comment]
I have pushed some other changes:
- https://github.com/REDasmOrg/REDasm-Library/commit/637fc9a4a962248e4ba38292a8aae735226cf8cc
- https://github.com/REDasmOrg/REDasm/commit/dbb248e54714b0fd6fe1339b3ec77002b129ca8a

**Comment by danfe** [comment]
No problem, take your time.  Also note that if you need signed type for some reason which is bitwidth-compatible with `size_t` there is `ssize_t`.

**Comment by Dax89** [comment]
Mmmh, afaik `ssize_t` is a non standard type, but I think that I don't need a signed type (for now).

**Comment by danfe** [comment]
I'm also not a big fan of non-standard types but thought that was the reason why you had to reintroduce the cast back in commit f8a785c, because of `s64 length()`.  Typically though, length-type of functions should return `size_t`, cf. `strlen(3)` et al.

**Comment by Dax89** [comment]
I have removed more misused `u64` types along with a bunch of other fixes, I will release a hotfixed version this week, let me know if you have other compilation issues!

**Comment by danfe** [comment]
Thanks, both builds on i386 and amd64 are fine now without any patches.  I've noticed something strange though: the call graph (same binary, same function) in version 2.0 looks more analysed and detailed compared to the 2.1 one.  I'm attaching both screenshots for you to take a look.

![Version 2.0](https://user-images.githubusercontent.com/1132291/57865951-19050200-7831-11e9-8e5e-8a2a7cf846a6.png)_Fig.1_ Version 2.0

![Version 2.1](https://user-images.githubusercontent.com/1132291/57865952-199d9880-7831-11e9-88bf-bc2018b0b626.png)_Fig.2_ Version 2.1

**Comment by Dax89** [comment]
Looks like a regression, is it possible to share the binary? 

> P.S. Tell me if I should rather open a separate issue for this.
No problem, we can continue here

**Comment by danfe** [comment]
Yes, it's surely possible, it's just a `/bin/dd` from my FreeBSD/i386 13.0-CURRENT work computer.  Unfortunately, I cannot access the machine right now, I can only do that tomorrow.  If you'd rather not wait, you can fetch some recent FreeBSD/i386 snapshot and get it from there.

**Comment by Dax89** [comment]
No problem, I can wait! :+1:

**Comment by danfe** [comment]
This is a [gzip'ed](https://github.com/REDasmOrg/REDasm/files/3190581/dd.gz) `/bin/dd` binary I used for tests.

**Comment by Dax89** [comment]
Mmmh, I have a question: those screenshots comes from 32-bit version of redasm?

![Screenshot_20190517_135743](https://user-images.githubusercontent.com/1503603/57926599-febc3a00-78ab-11e9-97b8-77a2d201160d.png)

It looks fine on 64 bit, it may be another `u64` vs `size_t` conversion

**Comment by danfe** [comment]
Yes, my environment is almost strictly 32-bit, I can only build-test amd64.  FWIW, I've noticed this bug with vanilla 2.1, prior to your recent `u64` vs `size_t` changes.

I'll try to find amd64 computer to test 64-bit version; meanwhile, you can try 32-bit in your VM.

**Comment by Dax89** [comment]
Ok, I have tested REDasm in a 32 bit enviromnent and looks like that the issue is fixed, can you confirm?
Thanks.

![Screenshot_20190523_150438](https://user-images.githubusercontent.com/1503603/58254924-227bf600-7d6c-11e9-9f3f-3660a0455591.png)

**Comment by danfe** [comment]
I confirm, it looks good now.

**Comment by Dax89** [comment]
Great! Thanks for the support :+1:
