### ISSUE TITLE
Failed to clone 'sdk'

### ISSUE THREAD

**Issue by blshkv** [REDasmOrg/REDasm#29]
This is a special case probably, and it happens only when I refuse enter my github passwords:
```
Cloning into '/tmp/REDasm/REDasm/LibREDasm/sdk'...
sign_and_send_pubkey: signing failed: agent refused operation
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:REDasmOrg/REDasm-SDK.git' into submodule path '/tmp/REDasm/REDasm/LibREDasm/sdk' failed
```

Could you please change the link from git@ to https:// to be consistent?

**Comment by blshkv** [comment]
I'm wrong, it happens during the automated (batch) build too where I'm unable to answer "yes" and cloning is getting stuck:

```
 * Fetching .[1mgit@github.com:REDasmOrg/REDasm-SDK.git.[22m ...                                         
git fetch git@github.com:REDasmOrg/REDasm-SDK.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/ta
gs/* +refs/notes/*:refs/notes/* +HEAD:refs/git-r3/HEAD                                                   
The authenticity of host 'github.com (140.82.118.4)' can't be established.                               
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.                               
Are you sure you want to continue connecting (yes/no)?
```

**Comment by Dax89** [comment]
You can use the https version: `https://github.com/REDasmOrg/REDasm.git`

It's better to clone the tagged version (https://github.com/REDasmOrg/REDasm/tree/v2.1.1) because in upstream I'm changing some things in order to support plugins and python scripting.

**Comment by blshkv** [comment]
This is exactly how I run it, however the link ```https://github.com/REDasmOrg/REDasm-Library/``` points to  git@, there is nothing I can do here

**Comment by Dax89** [comment]
I have removed the 'sdk' submodule, it should work now!

**Comment by blshkv** [comment]
Great, thanks
