### ISSUE TITLE
not runing

### ISSUE THREAD

**Issue by jj77k22k** [REDasmOrg/REDasm#35]
Hi bro
I have a WIN7 x32bit OS installed on my PC & whene i run REDasm.exe it send to me this MSG
![error](https://user-images.githubusercontent.com/49036069/79149655-c4af2d00-7dc7-11ea-8a30-be6f6ff502e2.PNG)
what's the solution plz?

**Comment by Dax89** [comment]
You are trying to execute redasm 64 bit in a 32bit os
