### ISSUE TITLE
v2.1.1 no longer compile

### ISSUE THREAD

**Issue by FabioLolix** [REDasmOrg/REDasm#42]
Ciao Davide :)

I'm the AUR packager of the stable version of redasm

Recently it has been reported that it no longer compile on Arch & derivates (I'm currently using Manjaro Linux)

The specific error is:

```
/home/fabio/Dev/Github/PKGBUILD/redasm/src/REDasm/widgets/disassemblerlistingview/disassemblercolumnview.cpp:133:18: error: aggregate ‘QPainterPath path’ has incomplete type and cannot be defined
  133 |     QPainterPath path;
      |                  ^~~~
```

The AUR pkgbuild is currently missing proper download and configuration of 1 git submodule, which has been corrected here 
https://github.com/FabioLolix/PKGBUILD/blob/master/redasm/PKGBUILD

**Comment by Dax89** [comment]
Ciao Fabio! :D

I have added the missing include and marked that "release" as "2.1.1-fix": https://github.com/REDasmOrg/REDasm/releases/tag/v2.1.1-fix

This stable release will be replaced with the new 3.0 soon

**Comment by FabioLolix** [comment]
Updated, Thanks.
