### ISSUE TITLE
 fatal error: tbb/blocked_range.h: No such file or directory

### ISSUE THREAD

**Issue by blshkv** [REDasmOrg/REDasm#43]
The latest 3.0.0 beta1 requires tbb library but there is no check in the CMakeLists.txt.
If not installed, the compilation fails with this error.

**Comment by Dax89** [comment]
Added TBB and Threads requirement in: https://github.com/REDasmOrg/REDasm-Library/commit/b9b9b2b8ebda1bb16329ec3ea9cdcae101b26e65

**Comment by blshkv** [comment]
Thanks
