### ISSUE TITLE
URL to download beta5 with all submodules in a tarball format

### ISSUE THREAD

**Issue by kermitdafrog8** [REDasmOrg/REDasm#45]
Looking for a way to download the full project as a source tarball with all submodules.  Thanks. When I download from Github it doesn't include the submodules.

**Comment by Dax89** [comment]
Have you looked here? https://github.com/REDasmOrg/REDasm/blob/master/COMPILE.md
BETA 5 is not released (yet) so it's just the last commit.

If you are just interested to try the latest features you can grab a nightly build here: https://github.com/REDasmOrg/REDasm/actions/workflows/build.yml

**Comment by kermitdafrog8** [comment]
I need it to be a full tarball with all submodules if possible.

**Comment by Dax89** [comment]
afaik github doesn't allow this

**Comment by alexmyczko** [comment]
i'd really like 3.x released...

**Comment by kermitdafrog8** [comment]
> afaik github doesn't allow this

I had to clone recursively the Github repository and manually create the source tarball with all submodules.

**Comment by Dax89** [comment]
Ok, so can I close this issue?
