### ISSUE TITLE
CreateFile2 could not be located in kernel32.dll + hacky fix

### ISSUE THREAD

**Issue by r3sus** [REDasmOrg/REDasm#47]
Hello.

I'm experiencing this error on my Win 7 machine. 

The fix, to be applied on LibREDasm.dll: 
https://steamcommunity.com/app/1580790/discussions/0/5079478487781475412/

Executable launches now. But doesn't seem to function. 

Thanks.

**Comment by Dax89** [comment]
I have done some fixes, check the latest build: https://github.com/REDasmOrg/REDasm/actions/runs/1127084696

It works on my Windows 7 VM now:
![Screenshot_20210813_110203](https://user-images.githubusercontent.com/1503603/129335572-114b160e-c1b3-4c9d-a14e-c8671f2d22d7.png)

**NOTE**
You need to install Visual C++ Redistributable 2019 too: https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

**Comment by r3sus** [comment]
Thank you kindly, it works now. But crashed on "Searching vtables":
[x1.txt](https://github.com/REDasmOrg/REDasm/files/6984926/x1.txt)
10 MB game executable

**Comment by Dax89** [comment]
Can you send me the 10MB executable via email (if possible)?

60MB executable is huge: currently REDasm is not highly optimized for ram usage, it needs some kind of disk caching system and some internal changes.

**Comment by r3sus** [comment]
Sure, sent. 
Got it.
Thanks.

**Comment by Dax89** [comment]
Ok, I can reproduce the crash on Windows 7 and 10, it doesn't happen on Linux

I'm fixing it.

**Comment by r3sus** [comment]
Worked fine on the subject 15 Mb executable. Thanks.
Sorry for late check, thought fix was not ready yet.

**Comment by markjanecki** [comment]
Hello Again 
I somehow got the fix to work maybe I was not looking in the correct file before (actually I  think that is what happened) sorry to bother you
