### ISSUE TITLE
source does not compile

### ISSUE THREAD

**Issue by kermitdafrog8** [REDasmOrg/REDasm#48]
When downloading source code from the release page it will not compile.  Missing submodules.

**Comment by Dax89** [comment]
The tarbal provided by GitHub doesn't includes submodules, you can download the BETA 5 source code along with its submodules with the following commands:

```
git clone https://github.com/REDasmOrg/REDasm.git
cd REDasm
git checkout v3.0.0-beta5
git submodule update --init 
```

**Comment by kermitdafrog8** [comment]
Just letting you know the source tarball in the release area is incomplete as is
