### ISSUE TITLE
Can not run\open any version after 2

### ISSUE THREAD

**Issue by markjanecki** [REDasmOrg/REDasm#53]

**Comment by markjanecki** [comment]
Entry point not found The procedure entry point CreateFile2 could not be located in the dynamic link library Kernel32.dll 
This is the error message

**Comment by Dax89** [comment]
Duplicate of: https://github.com/REDasmOrg/REDasm/issues/47

**Comment by markjanecki** [comment]
I tried to do what you told me but I could not find the object you told me to look for. I am wondering if this program works only on Windows versions larger than 7 and I am running 7 pro 64 bit
