### ISSUE TITLE
strings only in .rdata

### ISSUE THREAD

**Issue by tex** [REDasmOrg/REDasm#54]
Strings tab shows strings in only .rdata.
My binary has some strings in custom section. The section is recognized as CODE.
It would be nice to see strings in all sections.

**Comment by Dax89** [comment]
I need some informations:
- REDasm version
- Loader used (I assume PE)
- Assembler used (I assume x86_64)
- Is it possible to have the sample executable so I can check that?

**Comment by tex** [comment]
![image](https://user-images.githubusercontent.com/27386/164648424-f6db6485-5d96-4267-bd2e-ee6ccd276fa1.png)
[test1.perses.zip](https://github.com/REDasmOrg/REDasm/files/8538624/test1.perses.zip)

**Comment by Dax89** [comment]
Ok, thanks!

I have removed the shared file from your message

**Comment by tex** [comment]
It prints 4 "Hello world" strings :) But good you removed it anyway!

**Comment by Dax89** [comment]
Ok!

You are using a super old version: you can grab the 3.0 BETA 5 [here](https://github.com/REDasmOrg/REDasm/releases/tag/v3.0.0-beta5) or a nightly build (BETA 6, which is in development) from [CI](https://github.com/REDasmOrg/REDasm/actions/workflows/build.yml)

**Comment by tex** [comment]
Oh, I feel dumb :) I just did `scoop install redasm` and expected it to be somewhat up-to-date. The 3.0 works and I see strings. Thanks and sorry for interruption!

**Comment by tex** [comment]
BTW: Very nice analyzer!
