### ISSUE TITLE
Crashes on Disassembling File - 3.0-BETA6 (20221016.fc73e1c)

### ISSUE THREAD

**Issue by paulmcquad** [REDasmOrg/REDasm#58]
I try to Diassemble a ELF file but it crashes. I Compiled REDasm on Linux today.

`
build]$ ./REDasm

terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
Aborted (core dumped)
`

**Comment by Dax89** [comment]
Can I have the sample? (If it can be shared)

**Comment by paulmcquad** [comment]
I tried a system program like

/usr/bin/mkdir
