### ISSUE TITLE
Compile error "graphview.cpp:13:56: error: ‘ShowScrollBars’ is not a member of ‘QWebEngineSettings’"

### ISSUE THREAD

**Issue by pfalcon** [REDasmOrg/REDasm#6]
Well, master 05a2a4615462e1547756aa2a1709f8bcb01d2da8 (HEAD as of now). Given that there're no real build instructions (see https://github.com/REDasmOrg/REDasm/issues/2#issuecomment-436524923), I just used Dockerfile for a list of packages to install on my Ubuntu 18.04. The version I then have are:

~~~
ii  cmake                       3.10.2-1ubuntu2    amd64              cross-platform, open-source make system
ii  g++                         4:7.3.0-3ubuntu2.1 amd64              GNU C++ compiler
ii  git                         1:2.17.1-1ubuntu0. amd64              fast, scalable, distributed revision control system
ii  libqt5webenginewidgets5:amd 5.9.5+dfsg-0ubuntu amd64              Web content engine library for Qt - Widget
ii  qt5-default:amd64           5.9.5+dfsg-0ubuntu amd64              Qt 5 development defaults package
ii  qt5-qmake:amd64             5.9.5+dfsg-0ubuntu amd64              Qt 5 qmake Makefile generator tool
ii  qtwebengine5-dev:amd64      5.9.5+dfsg-0ubuntu amd64              Web content engine library for Qt - development files
~~~

So:

~~~
$ qmake && make
...
g++ -c -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DGIT_VERSION=\"05a2a46\" -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WEBENGINEWIDGETS_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_WEBENGINE_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB -I. -Idepends/include -Idepends/capstone/include/capstone -Iwidgets/QHexEdit -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebEngine -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebChannel -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtPositioning -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o graphview.o widgets/graphview/graphview.cpp
widgets/graphview/graphview.cpp: In constructor ‘GraphView::GraphView(QWidget*)’:
widgets/graphview/graphview.cpp:13:56: error: ‘ShowScrollBars’ is not a member of ‘QWebEngineSettings’
     this->settings()->setAttribute(QWebEngineSettings::ShowScrollBars, false);
                                                        ^~~~~~~~~~~~~~
widgets/graphview/graphview.cpp: In member function ‘void GraphView::zoomOn(int)’:
widgets/graphview/graphview.cpp:49:28: warning: unused parameter ‘line’ [-Wunused-parameter]
 void GraphView::zoomOn(int line)
                            ^~~~
Makefile:3411: recipe for target 'graphview.o' failed
make: *** [graphview.o] Error 1
~~~

P.S. Not surprised at all of course, it wouldn't be C++ with Qt if it just built ;-)

**Comment by pfalcon** [comment]
From: http://doc.qt.io/qt-5/qwebenginesettings.html

> QWebEngineSettings::ShowScrollBars | 25 | Shows scroll bars. Enabled by default. (Added in Qt 5.10)
-- | -- | --

From README:

> Qt >= 5.6

And CI doesn't even catch that...

**Comment by pfalcon** [comment]
Commenting that out, it didn't go too far:

~~~
widgets/disassemblerlistingview/disassemblertextview.cpp: In member function ‘bool DisassemblerTextView::isColumnVisible(int, int*)’:
widgets/disassemblerlistingview/disassemblertextview.cpp:412:35: error: ‘class QFontMetrics’ has no member named ‘horizontalAdvance’
     int adv = this->fontMetrics().horizontalAdvance(" ");
                                   ^~~~~~~~~~~~~~~~~
~~~

**Comment by pfalcon** [comment]
Ok, patching that out, finally there. I don't know what other people would do next, but for me, it's obvious:

~~~
./REDasm REDasm 
~~~

Well, nothing.

The feeling of dejavu is now 100%: https://github.com/wisk/medusa/issues/17

**Comment by Dax89** [comment]
> From: http://doc.qt.io/qt-5/qwebenginesettings.html
> 
> > QWebEngineSettings::ShowScrollBars | 25 | Shows scroll bars. Enabled by default. (Added in Qt 5.10)
> > -- | -- | --
> 
> From README:
> 
> > Qt >= 5.6
> 
> And CI doesn't even catch that...

It's just an oversight, because I have upgraded Qt recently...

> Ok, patching that out, finally there. I don't know what other people would do next, but for me, it's obvious:
> 
> ```
> ./REDasm REDasm 
> ```
> 
> Well, nothing.
> 
> The feeling of dejavu is now 100%: [wisk/medusa#17](https://github.com/wisk/medusa/issues/17)

It's easy to add argument support from command line.
It wasn't a priority, but I can add that, no problem.

> Commenting that out, it didn't go too far:
> 
> ```
> widgets/disassemblerlistingview/disassemblertextview.cpp: In member function ‘bool DisassemblerTextView::isColumnVisible(int, int*)’:
> widgets/disassemblerlistingview/disassemblertextview.cpp:412:35: error: ‘class QFontMetrics’ has no member named ‘horizontalAdvance’
>      int adv = this->fontMetrics().horizontalAdvance(" ");
>                                    ^~~~~~~~~~~~~~~~~
> ```

`QFontMetrics.:horizontalAdvance` is introduced in Qt 5.11 which deprecates `QFontMetrics::width`, I can replace it with `QFontMetrics::boundingRect` which makes REDasm compatible with Qt 5.10 (you know, WebEngine's scrollbars...)

As I wrote in README file, REDasm can be compiled by cloning the repo and executing `qmake` and `make`.
QMake will handle capstone compilation too. 

If those steps doesn't work out of the box, than it's an issue.
